In [2]:
from tensorflow.data import Dataset

In [15]:
dataset = Dataset.range(10)

for v in dataset:
    print(v.numpy())

0
1
2
3
4
5
6
7
8
9


In [32]:
tw = dataset.window(5, shift=1,stride=1,drop_remainder=True)

for v in tw:
    for e in v:
        print(e.numpy(), end=' ')
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [197]:
fm = tw.flat_map(lambda w:w.batch(5))
for i,v in enumerate(fm):
    print(i,v.numpy())

0 [0 1 2 3 4]
1 [1 2 3 4 5]
2 [2 3 4 5 6]
3 [3 4 5 6 7]
4 [4 5 6 7 8]
5 [5 6 7 8 9]


In [42]:
x_y = fm.map(lambda w:(w[:-1],w[-1]))
for x,y in x_y:
    print(x.numpy(),y.numpy())

[0 1 2 3] 4
[1 2 3 4] 5
[2 3 4 5] 6
[3 4 5 6] 7
[4 5 6 7] 8
[5 6 7 8] 9


In [174]:
shuffle = x_y.shuffle(buffer_size=2)

for x,y in shuffle:
    print(x.numpy(),y.numpy())

[0 1 2 3] 4
[1 2 3 4] 5
[3 4 5 6] 7
[4 5 6 7] 8
[5 6 7 8] 9
[2 3 4 5] 6


In [194]:
batch = shuffle.batch(3).prefetch(2)
for x,y in batch:
    print(x.numpy(),y.numpy())

[[0 1 2 3]
 [1 2 3 4]
 [3 4 5 6]] [4 5 7]
[[4 5 6 7]
 [5 6 7 8]
 [2 3 4 5]] [8 9 6]


In [189]:
batch.prefetch?
